author: GameAPI
authors: [Joba]
description: SpleefLeague Game API
main: com.spleefleague.gameapi.GameAPI
name: GameAPI
url: https://www.spleefleague.com/
version: 1.4
api-version: 1.13
softdepend: [SpleefLeagueCore, ProtocolLib, FakeBlocks]
loadbefore: [Commands, Parkour, SuperSpleef]